name: Download and Push File

on:
  schedule:
  - cron: '0 0 * * *' # At 00:00 on Monday
  workflow_dispatch:
jobs: 
  wget:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: setup git config
      run: |
          # 'GitHub Actions Bot' with no email by default
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          wget -X GET https://api.tmwstw.io/faucet_data -O current.json
          git add current.json
          git commit -snm "new data commit" || true
          git push origin main 
